### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lluiscab** [andrewrk/mcserve#18]
That's not an "issue" but I'd like you to explain how this works. Could you explain a bit what everything does? I've seen some type of proxy but I'm not sure of what it is supossed to do ;)

**Comment by thejoshwolfe** [comment]
First of all, this project was last updated for a very old version of Minecraft. It surely doesn't work with today's Minecraft. Plus, as neither of the original maintainers of this project play Minecraft anymore, this project will not be updated any time soon.

But if you're looking to update it yourself and you want to know a little bit more about it, I'd start by reading the readme, and ask any specific questions you might have in this issue.

**Comment by andrewrk** [comment]
You might reach out to the mineflayer project https://github.com/PrismarineJS/mineflayer

**Comment by lluiscab** [comment]
Okay, I came up with an idea of how this works, does it proxy from a js server to a java server so the java server managea everything and the js server can interact with the data?
